stringtie 10_week_post_conception-forebrain.bam -p 8 --conservative -l 10_week_post_conception-forebrain -o 10_week_post_conception-forebrain.gtf
stringtie 10_week_post_conception-heart.bam -p 8 --conservative -l 10_week_post_conception-heart -o 10_week_post_conception-heart.gtf
stringtie 10_week_post_conception-hindbrain.bam -p 8 --conservative -l 10_week_post_conception-hindbrain -o 10_week_post_conception-hindbrain.gtf
stringtie 10_week_post_conception-kidney.bam -p 8 --conservative -l 10_week_post_conception-kidney -o 10_week_post_conception-kidney.gtf
stringtie 10_week_post_conception-liver.bam -p 8 --conservative -l 10_week_post_conception-liver -o 10_week_post_conception-liver.gtf
stringtie 10_week_post_conception-ovary.bam -p 8 --conservative -l 10_week_post_conception-ovary -o 10_week_post_conception-ovary.gtf
stringtie 10_week_post_conception-testis.bam -p 8 --conservative -l 10_week_post_conception-testis -o 10_week_post_conception-testis.gtf
stringtie 11_week_post_conception-forebrain.bam -p 8 --conservative -l 11_week_post_conception-forebrain -o 11_week_post_conception-forebrain.gtf
stringtie 11_week_post_conception-heart.bam -p 8 --conservative -l 11_week_post_conception-heart -o 11_week_post_conception-heart.gtf
stringtie 11_week_post_conception-hindbrain.bam -p 8 --conservative -l 11_week_post_conception-hindbrain -o 11_week_post_conception-hindbrain.gtf
stringtie 11_week_post_conception-kidney.bam -p 8 --conservative -l 11_week_post_conception-kidney -o 11_week_post_conception-kidney.gtf
stringtie 11_week_post_conception-liver.bam -p 8 --conservative -l 11_week_post_conception-liver -o 11_week_post_conception-liver.gtf
stringtie 11_week_post_conception-ovary.bam -p 8 --conservative -l 11_week_post_conception-ovary -o 11_week_post_conception-ovary.gtf
stringtie 11_week_post_conception-testis.bam -p 8 --conservative -l 11_week_post_conception-testis -o 11_week_post_conception-testis.gtf
stringtie 12_week_post_conception-forebrain.bam -p 8 --conservative -l 12_week_post_conception-forebrain -o 12_week_post_conception-forebrain.gtf
stringtie 12_week_post_conception-heart.bam -p 8 --conservative -l 12_week_post_conception-heart -o 12_week_post_conception-heart.gtf
stringtie 12_week_post_conception-hindbrain.bam -p 8 --conservative -l 12_week_post_conception-hindbrain -o 12_week_post_conception-hindbrain.gtf
stringtie 12_week_post_conception-kidney.bam -p 8 --conservative -l 12_week_post_conception-kidney -o 12_week_post_conception-kidney.gtf
stringtie 12_week_post_conception-liver.bam -p 8 --conservative -l 12_week_post_conception-liver -o 12_week_post_conception-liver.gtf
stringtie 12_week_post_conception-ovary.bam -p 8 --conservative -l 12_week_post_conception-ovary -o 12_week_post_conception-ovary.gtf
stringtie 12_week_post_conception-testis.bam -p 8 --conservative -l 12_week_post_conception-testis -o 12_week_post_conception-testis.gtf
stringtie 13_week_post_conception-forebrain.bam -p 8 --conservative -l 13_week_post_conception-forebrain -o 13_week_post_conception-forebrain.gtf
stringtie 13_week_post_conception-heart.bam -p 8 --conservative -l 13_week_post_conception-heart -o 13_week_post_conception-heart.gtf
stringtie 13_week_post_conception-hindbrain.bam -p 8 --conservative -l 13_week_post_conception-hindbrain -o 13_week_post_conception-hindbrain.gtf
stringtie 13_week_post_conception-kidney.bam -p 8 --conservative -l 13_week_post_conception-kidney -o 13_week_post_conception-kidney.gtf
stringtie 13_week_post_conception-liver.bam -p 8 --conservative -l 13_week_post_conception-liver -o 13_week_post_conception-liver.gtf
stringtie 13_week_post_conception-ovary.bam -p 8 --conservative -l 13_week_post_conception-ovary -o 13_week_post_conception-ovary.gtf
stringtie 13_week_post_conception-testis.bam -p 8 --conservative -l 13_week_post_conception-testis -o 13_week_post_conception-testis.gtf
stringtie 16_week_post_conception-forebrain.bam -p 8 --conservative -l 16_week_post_conception-forebrain -o 16_week_post_conception-forebrain.gtf
stringtie 16_week_post_conception-heart.bam -p 8 --conservative -l 16_week_post_conception-heart -o 16_week_post_conception-heart.gtf
stringtie 16_week_post_conception-hindbrain.bam -p 8 --conservative -l 16_week_post_conception-hindbrain -o 16_week_post_conception-hindbrain.gtf
stringtie 16_week_post_conception-kidney.bam -p 8 --conservative -l 16_week_post_conception-kidney -o 16_week_post_conception-kidney.gtf
stringtie 16_week_post_conception-liver.bam -p 8 --conservative -l 16_week_post_conception-liver -o 16_week_post_conception-liver.gtf
stringtie 16_week_post_conception-ovary.bam -p 8 --conservative -l 16_week_post_conception-ovary -o 16_week_post_conception-ovary.gtf
stringtie 16_week_post_conception-testis.bam -p 8 --conservative -l 16_week_post_conception-testis -o 16_week_post_conception-testis.gtf
stringtie 18_week_post_conception-forebrain.bam -p 8 --conservative -l 18_week_post_conception-forebrain -o 18_week_post_conception-forebrain.gtf
stringtie 18_week_post_conception-heart.bam -p 8 --conservative -l 18_week_post_conception-heart -o 18_week_post_conception-heart.gtf
stringtie 18_week_post_conception-kidney.bam -p 8 --conservative -l 18_week_post_conception-kidney -o 18_week_post_conception-kidney.gtf
stringtie 18_week_post_conception-liver.bam -p 8 --conservative -l 18_week_post_conception-liver -o 18_week_post_conception-liver.gtf
stringtie 18_week_post_conception-ovary.bam -p 8 --conservative -l 18_week_post_conception-ovary -o 18_week_post_conception-ovary.gtf
stringtie 18_week_post_conception-testis.bam -p 8 --conservative -l 18_week_post_conception-testis -o 18_week_post_conception-testis.gtf
stringtie 19_week_post_conception-forebrain.bam -p 8 --conservative -l 19_week_post_conception-forebrain -o 19_week_post_conception-forebrain.gtf
stringtie 19_week_post_conception-heart.bam -p 8 --conservative -l 19_week_post_conception-heart -o 19_week_post_conception-heart.gtf
stringtie 19_week_post_conception-kidney.bam -p 8 --conservative -l 19_week_post_conception-kidney -o 19_week_post_conception-kidney.gtf
stringtie 19_week_post_conception-liver.bam -p 8 --conservative -l 19_week_post_conception-liver -o 19_week_post_conception-liver.gtf
stringtie 19_week_post_conception-testis.bam -p 8 --conservative -l 19_week_post_conception-testis -o 19_week_post_conception-testis.gtf
stringtie 4_week_post_conception-forebrain.bam -p 8 --conservative -l 4_week_post_conception-forebrain -o 4_week_post_conception-forebrain.gtf
stringtie 4_week_post_conception-heart.bam -p 8 --conservative -l 4_week_post_conception-heart -o 4_week_post_conception-heart.gtf
stringtie 4_week_post_conception-hindbrain.bam -p 8 --conservative -l 4_week_post_conception-hindbrain -o 4_week_post_conception-hindbrain.gtf
stringtie 4_week_post_conception-kidney.bam -p 8 --conservative -l 4_week_post_conception-kidney -o 4_week_post_conception-kidney.gtf
stringtie 4_week_post_conception-liver.bam -p 8 --conservative -l 4_week_post_conception-liver -o 4_week_post_conception-liver.gtf
stringtie 4_week_post_conception-ovary.bam -p 8 --conservative -l 4_week_post_conception-ovary -o 4_week_post_conception-ovary.gtf
stringtie 4_week_post_conception-testis.bam -p 8 --conservative -l 4_week_post_conception-testis -o 4_week_post_conception-testis.gtf
stringtie 5_week_post_conception-forebrain.bam -p 8 --conservative -l 5_week_post_conception-forebrain -o 5_week_post_conception-forebrain.gtf
stringtie 5_week_post_conception-heart.bam -p 8 --conservative -l 5_week_post_conception-heart -o 5_week_post_conception-heart.gtf
stringtie 5_week_post_conception-hindbrain.bam -p 8 --conservative -l 5_week_post_conception-hindbrain -o 5_week_post_conception-hindbrain.gtf
stringtie 5_week_post_conception-kidney.bam -p 8 --conservative -l 5_week_post_conception-kidney -o 5_week_post_conception-kidney.gtf
stringtie 5_week_post_conception-liver.bam -p 8 --conservative -l 5_week_post_conception-liver -o 5_week_post_conception-liver.gtf
stringtie 5_week_post_conception-ovary.bam -p 8 --conservative -l 5_week_post_conception-ovary -o 5_week_post_conception-ovary.gtf
stringtie 5_week_post_conception-testis.bam -p 8 --conservative -l 5_week_post_conception-testis -o 5_week_post_conception-testis.gtf
stringtie 6_week_post_conception-heart.bam -p 8 --conservative -l 6_week_post_conception-heart -o 6_week_post_conception-heart.gtf
stringtie 6_week_post_conception-hindbrain.bam -p 8 --conservative -l 6_week_post_conception-hindbrain -o 6_week_post_conception-hindbrain.gtf
stringtie 6_week_post_conception-kidney.bam -p 8 --conservative -l 6_week_post_conception-kidney -o 6_week_post_conception-kidney.gtf
stringtie 6_week_post_conception-liver.bam -p 8 --conservative -l 6_week_post_conception-liver -o 6_week_post_conception-liver.gtf
stringtie 6_week_post_conception-ovary.bam -p 8 --conservative -l 6_week_post_conception-ovary -o 6_week_post_conception-ovary.gtf
stringtie 6_week_post_conception-testis.bam -p 8 --conservative -l 6_week_post_conception-testis -o 6_week_post_conception-testis.gtf
stringtie 7_week_post_conception-forebrain.bam -p 8 --conservative -l 7_week_post_conception-forebrain -o 7_week_post_conception-forebrain.gtf
stringtie 7_week_post_conception-heart.bam -p 8 --conservative -l 7_week_post_conception-heart -o 7_week_post_conception-heart.gtf
stringtie 7_week_post_conception-hindbrain.bam -p 8 --conservative -l 7_week_post_conception-hindbrain -o 7_week_post_conception-hindbrain.gtf
stringtie 7_week_post_conception-kidney.bam -p 8 --conservative -l 7_week_post_conception-kidney -o 7_week_post_conception-kidney.gtf
stringtie 7_week_post_conception-liver.bam -p 8 --conservative -l 7_week_post_conception-liver -o 7_week_post_conception-liver.gtf
stringtie 7_week_post_conception-ovary.bam -p 8 --conservative -l 7_week_post_conception-ovary -o 7_week_post_conception-ovary.gtf
stringtie 7_week_post_conception-testis.bam -p 8 --conservative -l 7_week_post_conception-testis -o 7_week_post_conception-testis.gtf
stringtie 8_week_post_conception-forebrain.bam -p 8 --conservative -l 8_week_post_conception-forebrain -o 8_week_post_conception-forebrain.gtf
stringtie 8_week_post_conception-heart.bam -p 8 --conservative -l 8_week_post_conception-heart -o 8_week_post_conception-heart.gtf
stringtie 8_week_post_conception-hindbrain.bam -p 8 --conservative -l 8_week_post_conception-hindbrain -o 8_week_post_conception-hindbrain.gtf
stringtie 8_week_post_conception-kidney.bam -p 8 --conservative -l 8_week_post_conception-kidney -o 8_week_post_conception-kidney.gtf
stringtie 8_week_post_conception-liver.bam -p 8 --conservative -l 8_week_post_conception-liver -o 8_week_post_conception-liver.gtf
stringtie 8_week_post_conception-ovary.bam -p 8 --conservative -l 8_week_post_conception-ovary -o 8_week_post_conception-ovary.gtf
stringtie 8_week_post_conception-testis.bam -p 8 --conservative -l 8_week_post_conception-testis -o 8_week_post_conception-testis.gtf
stringtie 9_week_post_conception-forebrain.bam -p 8 --conservative -l 9_week_post_conception-forebrain -o 9_week_post_conception-forebrain.gtf
stringtie 9_week_post_conception-heart.bam -p 8 --conservative -l 9_week_post_conception-heart -o 9_week_post_conception-heart.gtf
stringtie 9_week_post_conception-hindbrain.bam -p 8 --conservative -l 9_week_post_conception-hindbrain -o 9_week_post_conception-hindbrain.gtf
stringtie 9_week_post_conception-kidney.bam -p 8 --conservative -l 9_week_post_conception-kidney -o 9_week_post_conception-kidney.gtf
stringtie 9_week_post_conception-liver.bam -p 8 --conservative -l 9_week_post_conception-liver -o 9_week_post_conception-liver.gtf
stringtie 9_week_post_conception-ovary.bam -p 8 --conservative -l 9_week_post_conception-ovary -o 9_week_post_conception-ovary.gtf
stringtie 9_week_post_conception-testis.bam -p 8 --conservative -l 9_week_post_conception-testis -o 9_week_post_conception-testis.gtf
stringtie adolescent-forebrain.bam -p 8 --conservative -l adolescent-forebrain -o adolescent-forebrain.gtf
stringtie adolescent-heart.bam -p 8 --conservative -l adolescent-heart -o adolescent-heart.gtf
stringtie adolescent-hindbrain.bam -p 8 --conservative -l adolescent-hindbrain -o adolescent-hindbrain.gtf
stringtie adolescent-liver.bam -p 8 --conservative -l adolescent-liver -o adolescent-liver.gtf
stringtie adolescent-testis.bam -p 8 --conservative -l adolescent-testis -o adolescent-testis.gtf
stringtie elderly-forebrain.bam -p 8 --conservative -l elderly-forebrain -o elderly-forebrain.gtf
stringtie elderly-hindbrain.bam -p 8 --conservative -l elderly-hindbrain -o elderly-hindbrain.gtf
stringtie elderly-liver.bam -p 8 --conservative -l elderly-liver -o elderly-liver.gtf
stringtie elderly-testis.bam -p 8 --conservative -l elderly-testis -o elderly-testis.gtf
stringtie infant-forebrain.bam -p 8 --conservative -l infant-forebrain -o infant-forebrain.gtf
stringtie infant-heart.bam -p 8 --conservative -l infant-heart -o infant-heart.gtf
stringtie infant-hindbrain.bam -p 8 --conservative -l infant-hindbrain -o infant-hindbrain.gtf
stringtie infant-kidney.bam -p 8 --conservative -l infant-kidney -o infant-kidney.gtf
stringtie infant-liver.bam -p 8 --conservative -l infant-liver -o infant-liver.gtf
stringtie infant-testis.bam -p 8 --conservative -l infant-testis -o infant-testis.gtf
stringtie middle_adult-forebrain.bam -p 8 --conservative -l middle_adult-forebrain -o middle_adult-forebrain.gtf
stringtie middle_adult-heart.bam -p 8 --conservative -l middle_adult-heart -o middle_adult-heart.gtf
stringtie middle_adult-hindbrain.bam -p 8 --conservative -l middle_adult-hindbrain -o middle_adult-hindbrain.gtf
stringtie middle_adult-liver.bam -p 8 --conservative -l middle_adult-liver -o middle_adult-liver.gtf
stringtie middle_adult-testis.bam -p 8 --conservative -l middle_adult-testis -o middle_adult-testis.gtf
stringtie neonate-forebrain.bam -p 8 --conservative -l neonate-forebrain -o neonate-forebrain.gtf
stringtie neonate-heart.bam -p 8 --conservative -l neonate-heart -o neonate-heart.gtf
stringtie neonate-hindbrain.bam -p 8 --conservative -l neonate-hindbrain -o neonate-hindbrain.gtf
stringtie neonate-kidney.bam -p 8 --conservative -l neonate-kidney -o neonate-kidney.gtf
stringtie neonate-liver.bam -p 8 --conservative -l neonate-liver -o neonate-liver.gtf
stringtie school_age_child-forebrain.bam -p 8 --conservative -l school_age_child-forebrain -o school_age_child-forebrain.gtf
stringtie school_age_child-hindbrain.bam -p 8 --conservative -l school_age_child-hindbrain -o school_age_child-hindbrain.gtf
stringtie school_age_child-kidney.bam -p 8 --conservative -l school_age_child-kidney -o school_age_child-kidney.gtf
stringtie school_age_child-liver.bam -p 8 --conservative -l school_age_child-liver -o school_age_child-liver.gtf
stringtie toddler-forebrain.bam -p 8 --conservative -l toddler-forebrain -o toddler-forebrain.gtf
stringtie toddler-heart.bam -p 8 --conservative -l toddler-heart -o toddler-heart.gtf
stringtie toddler-hindbrain.bam -p 8 --conservative -l toddler-hindbrain -o toddler-hindbrain.gtf
stringtie toddler-kidney.bam -p 8 --conservative -l toddler-kidney -o toddler-kidney.gtf
stringtie toddler-liver.bam -p 8 --conservative -l toddler-liver -o toddler-liver.gtf
stringtie toddler-testis.bam -p 8 --conservative -l toddler-testis -o toddler-testis.gtf
stringtie young_adult-forebrain.bam -p 8 --conservative -l young_adult-forebrain -o young_adult-forebrain.gtf
stringtie young_adult-heart.bam -p 8 --conservative -l young_adult-heart -o young_adult-heart.gtf
stringtie young_adult-hindbrain.bam -p 8 --conservative -l young_adult-hindbrain -o young_adult-hindbrain.gtf
stringtie young_adult-liver.bam -p 8 --conservative -l young_adult-liver -o young_adult-liver.gtf
stringtie young_adult-testis.bam -p 8 --conservative -l young_adult-testis -o young_adult-testis.gtf
